

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jd?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: org.lanqiao.jd.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        jd:
          mapper : debug