server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jd?useUnicode=true&amp;characterEncoding=UTF8&amp;nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:org/lanqiao/jd/mapper/*.xml
  type-aliases-package: org.lanqiao.jd.entity

#showSql
logging:
  level:
    org.lanqiao.jd:
        mapper : debug