spring:
  datasource:
    username: root
    password: h123456
    url: jdbc:mysql://localhost:3306/jd?serverTimezone=GMT&amp;useUnicode=true&amp;characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.lanqiao.jd.entity,java.lang
#  type-aliases-package: java.lang
  mapper-locations: classpath:org/lanqiao/jd/mapper/*.xml

#showSql
logging:
  level:
    org.lanqiao.jd:
        mapper : debug
